# Generated by Django 4.2.2 on 2023-06-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='original_image', verbose_name='Orijinal Görsel')),
                ('bg_removed_image', models.ImageField(blank=True, null=True, upload_to='bg_removed_image', verbose_name='Arka Planı Silinmiş Görsel')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed_image', verbose_name='İşlenmiş Görsel')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='background_image', verbose_name='Arkaplan')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
