# Generated by Django 4.2.2 on 2023-06-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerequest',
            name='is_transparent',
            field=models.BooleanField(default=False),
        ),
    ]
